"""Agent name pool for random team creation.

Contains ~1000 short (<8 char), friendly names used when creating teams
with `--agents N` (numeric count).
"""

import random

# Pool of ~1000 short, friendly names
# All names are < 8 characters, lowercase alphanumeric only
AGENT_NAMES: tuple[str, ...] = (
    "alex", "avery", "bailey", "blake", "brynn", "casey", "charlie", "cleo",
    "corey", "dakota", "dana", "darcy", "drew", "ellis", "ember", "emery",
    "finn", "frankie", "gray", "harper", "hayden", "jade", "jamie", "jesse",
    "jordan", "jules", "kai", "kerry", "kit", "lane", "lee", "logan",
    "lou", "luna", "lynn", "mar", "max", "morgan", "neo", "noel",
    "nova", "olive", "parker", "pat", "peyton", "phoenix", "quinn", "ray",
    "reed", "reese", "remy", "riley", "river", "robin", "rowan", "ryan",
    "sage", "sam", "sawyer", "scout", "sean", "shadow", "sky", "sloan",
    "storm", "sydney", "tanner", "taylor", "teo", "terry", "val", "west",
    "wren", "yale", "zane", "adrian", "aiden", "alec", "allen", "andi",
    "andy", "angus", "ari", "ariel", "arlo", "ash", "asher", "atlas",
    "austin", "axel", "ben", "beau", "beck", "benny", "blair", "blaise",
    "blue", "bo", "bowie", "brady", "bram", "brent", "bret", "brett",
    "brock", "brook", "brooks", "bryce", "cade", "cai", "caleb", "calvin",
    "cam", "camden", "carl", "carmen", "carter", "cedar", "chance", "chase",
    "chris", "cisco", "clark", "clay", "cody", "cole", "colin", "colt",
    "connor", "cooper", "cosmo", "cruz", "curtis", "cy", "cyrus", "dale",
    "dallas", "dalton", "damon", "dan", "dane", "danny", "dante", "darren",
    "dash", "dave", "davis", "dax", "dean", "dennis", "denver", "derek",
    "devin", "devon", "dexter", "diego", "dillon", "dom", "donnie", "dorian",
    "doug", "drake", "duncan", "dustin", "dylan", "earl", "easton", "eddie",
    "eden", "edgar", "eli", "elias", "elijah", "elliot", "enzo", "eric",
    "erin", "ethan", "evan", "ezra", "felix", "flynn", "forest", "fox",
    "fred", "gabe", "gage", "gareth", "garrett", "gary", "gavin", "gene",
    "george", "gio", "glen", "glenn", "gordon", "grady", "grant", "grayson",
    "greg", "griffin", "gus", "hank", "harley", "harris", "harry", "harvey",
    "heath", "hector", "henry", "holden", "hudson", "hugo", "hunter", "ian",
    "ike", "isaac", "isaiah", "ivan", "jack", "jackson", "jacob", "jake",
    "jalen", "james", "jared", "jarrett", "jarvis", "jason", "jasper", "jax",
    "jaxon", "jay", "jayden", "jed", "jeff", "jeremy", "jett", "jim",
    "jimmy", "joel", "joey", "john", "jonah", "jonas", "josh", "joshua",
    "jude", "julian", "julius", "justin", "kade", "kaden", "kane", "karl",
    "keaton", "keith", "kellen", "kelsey", "kelvin", "ken", "kendall", "kenny",
    "kent", "kevin", "kieran", "kirk", "knox", "kobe", "kody", "kurt",
    "kyle", "kyler", "lance", "landen", "landon", "lars", "layton", "leo",
    "leon", "levi", "lewis", "liam", "lincoln", "linus", "lionel", "lloyd",
    "lucas", "luis", "luke", "mack", "magnus", "malone", "marc", "marco",
    "marcus", "mario", "mark", "marley", "marlon", "marq", "marvin", "mason",
    "mathew", "matt", "maurice", "maxim", "miles", "milo", "mitch", "morris",
    "moss", "murphy", "nate", "nathan", "neal", "ned", "neil", "nels",
    "nelson", "newton", "nico", "nick", "nicky", "nigel", "niko", "nolan",
    "norm", "norman", "oak", "odin", "omar", "orion", "orlando", "oscar",
    "otis", "otto", "owen", "pablo", "page", "palmer", "pascal", "patrick",
    "paul", "paxton", "percy", "perry", "pete", "peter", "phil", "pierce",
    "porter", "preston", "price", "prince", "quentin", "quincy", "rafael", "ralph",
    "ramon", "randall", "randy", "raul", "raven", "rex", "rhett", "rhys",
    "ricardo", "rich", "rick", "ricky", "ridge", "rigby", "roan", "rob",
    "robert", "rocco", "rock", "rocky", "rod", "rodney", "roger", "rojo",
    "roland", "roman", "romeo", "ronald", "rory", "ross", "royce", "rudi",
    "rudy", "rufus", "russell", "rusty", "ryder", "sal", "sammy", "samuel",
    "sanders", "santos", "saul", "saxon", "scott", "sergio", "seth", "shane",
    "shaun", "shawn", "shay", "shelby", "sid", "silas", "simon", "skyler",
    "slade", "smith", "solomon", "sonny", "spencer", "stan", "steele", "stefan",
    "steve", "steven", "sully", "sylvan", "tate", "ted", "teddy", "thane",
    "theo", "thomas", "thor", "tim", "timothy", "titus", "toby", "todd",
    "tom", "tommy", "tony", "trace", "travis", "trent", "trevor", "trey",
    "tristan", "troy", "tucker", "ty", "tyler", "tyrone", "tyson", "ulysses",
    "uri", "vance", "vaughn", "vernon", "vic", "vick", "victor", "vince",
    "vincent", "virgil", "wade", "walker", "wallace", "walt", "walter", "ward",
    "warner", "warren", "watson", "waylon", "wayne", "wells", "wendell", "werner",
    "wes", "wesley", "wiley", "will", "william", "willie", "wilson", "winston",
    "wyatt", "xavier", "xander", "yael", "yuri", "zach", "zachary", "zack",
    "zander", "zeke", "zeus", "acre", "alder", "amber", "anchor", "apple",
    "arch", "arrow", "aspen", "azure", "bark", "bay", "beach", "beam",
    "bear", "berry", "birch", "bird", "blaze", "bloom", "blossom", "bolt",
    "boulder", "branch", "breeze", "bridge", "bright", "bronze", "brush", "canyon",
    "cape", "cask", "castle", "cave", "cherry", "chill", "cinder", "circle",
    "city", "cliff", "cloud", "clover", "coast", "coral", "cosmos", "cove",
    "crane", "creek", "crest", "crimson", "crown", "crystal", "current", "cypress",
    "daisy", "dawn", "delta", "dew", "diamond", "dove", "dune", "dusk",
    "dust", "eagle", "earth", "echo", "edge", "elm", "ever", "fable",
    "falcon", "fawn", "fern", "field", "fire", "flame", "flash", "flint",
    "flood", "flora", "flower", "fog", "forge", "fort", "frost", "galaxy",
    "gale", "garden", "gate", "gem", "glacier", "glade", "glaze", "gleam",
    "glimmer", "globe", "glow", "gold", "grace", "grain", "granite", "grove",
    "gulf", "hail", "harbor", "harvest", "hawk", "haze", "haven", "hazel",
    "hearth", "heather", "hedge", "hill", "hollow", "honey", "horizon", "horn",
    "ice", "inlet", "iris", "iron", "island", "ivory", "jasmine", "jazz",
    "jewel", "kindle", "lake", "lark", "lava", "leaf", "ledge", "lily",
    "lime", "maple", "marble", "meadow", "mesa", "meteor", "mint", "mist",
    "moon", "mount", "nectar", "nest", "night", "north", "oasis", "ocean",
    "onyx", "opal", "oracle", "orchid", "owl", "palm", "panda", "panther",
    "pass", "path", "peak", "pearl", "pebble", "pepper", "petal", "pine",
    "pink", "plain", "planet", "plaza", "plume", "polar", "pond", "poppy",
    "prairie", "prism", "pulse", "quartz", "rain", "rainbow", "ranch", "range",
    "rapid", "reef", "rift", "ripple", "road", "rose", "ruby", "rush",
    "rust", "sand", "sands", "sea", "shell", "shore", "silver", "slate",
    "snow", "solar", "south", "spark", "sphere", "spike", "spirit", "spring",
    "spruce", "star", "steel", "stone", "strand", "stream", "summit", "sun",
    "sunset", "surf", "swift", "terra", "thistle", "thorn", "thunder", "tide",
    "timber", "topaz", "torch", "tower", "trail", "tree", "tropic", "tundra",
    "turbo", "turtle", "vale", "valley", "vapor", "vault", "velvet", "verde",
    "vista", "void", "wake", "wave", "wheat", "wild", "willow", "wind",
    "window", "wing", "winter", "wolf", "wood", "woods", "zephyr", "zinc",
    "abbey", "acorn", "agave", "alba", "alcove", "alpine", "alto", "alumni",
    "amazon", "ambush", "ames", "amigo", "amos", "amp", "andes", "angel",
    "angler", "antler", "anvil", "apex", "apollo", "arbor", "arcade", "archer",
    "arctic", "arena", "argent", "argon", "aria", "armor", "arthur", "ashby",
    "ashton", "astro", "athens", "athos", "atom", "auburn", "august", "aurora",
    "autumn", "avenue", "axe", "axiom", "babble", "badge", "baker", "balboa",
    "bali", "ballot", "bamboo", "bandit", "banner", "bard", "barge", "barley",
    "barn", "baron", "barrel", "barry", "barton", "basalt", "base", "basil",
    "basin", "basket", "bass", "batch", "baton", "baxter", "beacon", "bead",
    "beagle", "bean", "beast", "beech", "beef", "beetle", "bella", "belle",
    "bells", "bench", "bentley", "bergen", "bernie", "bess", "beta", "bevel",
    "bianca", "bike", "billow", "bingo", "bishop", "bison", "bixby", "bjorn",
    "black", "blade", "blanc", "blank", "blast", "blend", "bless", "blink",
    "bliss", "block", "blonde", "blood", "bluff", "board", "boat", "bobby",
    "boden", "body", "bogey", "bond", "bone", "bonnie", "bonus", "book",
    "boom", "boost", "booth", "boots", "border", "boris", "boston", "botany",
    "bottle", "bottom", "bounce", "bound", "bounty", "bow", "bowl", "box",
    "boyd", "brace", "bracket", "brad", "braid", "brain", "brake", "brand",
    "brass", "brave", "bread", "break", "breath", "breed", "brenda", "brew",
    "brian", "brick", "bride", "brill", "brine", "bring", "brink", "brisk",
    "brit", "broad", "brodie", "broke", "brooke", "brown", "bruce", "bruno",
    "bryan", "bubble", "buck", "bucky", "buddy", "buffer", "bug", "bugle",
    "build", "bulb", "bulk", "bull", "bullet", "bump", "bundle", "bunny",
    "buoy", "burden", "bureau", "burger", "burgess", "burke", "burn", "burns",
    "burst", "burton", "bus", "bush", "butler", "butter", "button", "buzz",
    "byron", "cab", "cabin", "cable", "cactus", "cadet", "cadmus", "cage",
    "cairo", "cake", "cali", "calla", "calm", "calypso", "camel", "cameo",
    "camera", "camp", "canal", "canary", "cancel", "cancer", "candle", "candy",
    "cane", "canoe", "canon", "canopy", "cant", "canvas", "cap", "capital",
    "capt", "capture", "carbon", "card", "care", "cargo", "carla", "carlo",
    "carlos", "carlton", "carmel", "carol", "carpet", "carrie", "carry", "carson",
    "cartel", "carver", "case", "cash", "casper", "cast", "casual", "cat",
    "catch", "cattle", "cause", "cecil", "cellar", "celtic", "cent", "center",
    "ceres", "chain", "chair", "chalk", "champ", "chanel", "change", "channel",
    "chant", "chaos", "chapel", "charge", "charm", "chart", "check", "cheek",
    "cheer", "chef", "chelsea", "cherish", "chess", "chest", "chief", "child",
    "chili", "chime", "china", "chip", "choice", "choir", "chord", "chorus",
    "chrome", "chuck", "chunk", "church", "cipher", "circus", "cite", "civic",
    "civil", "claim", "claire", "clam", "clancy", "clap", "clara", "clare",
    "clash", "clasp", "class", "claude", "clause", "claw", "clean", "clear",
    "clement", "clerk", "clever", "click", "client", "climb", "clinic", "clio",
    "clip", "cloak", "clock", "clone", "close", "cloth", "club", "clue",
    "coach", "coal", "coarse", "cobra", "code", "coen", "coffee", "coil",
    "coin", "cola", "cold", "colette", "collar", "collect", "college", "colon",
    "colony", "color", "colton", "column", "coma", "comb", "combat", "combo",
    "come", "comet", "comfort", "comic", "comma", "command", "common", "compact",
    "compass", "complex", "concept", "concern", "concert", "conduct", "cone", "congo",
    "conic", "connect", "conner", "connie", "conrad", "consist", "console", "consul",
    "contact", "contain", "content", "contest", "context", "contour", "control", "convert",
    "convex", "convoy", "cook", "cookie", "cool", "cope", "copper", "copy",
    "cord", "core", "cork", "corner", "corona", "corps", "correct", "cosine",
    "cosmic", "cost", "cottage", "cotton", "couch", "cougar", "could", "council",
    "count", "country", "county", "couple", "courage", "course", "court", "cousin",
    "cover", "covert", "cowboy", "craft", "craig", "cramp", "crash", "crater",
    "crave", "crawl", "crazy", "cream", "create", "credit", "creed", "creep",
    "crew", "cricket", "crime", "crisp", "critic", "crocus", "cross", "crowd",
    "crucial", "crude", "cruel", "cruise", "crumb", "crunch", "crusade", "crush",
    "crust", "cry", "crypto", "cube", "cubic", "cue", "cult", "culture",
    "cup", "cupid", "curb", "cure", "curious", "curl", "curve", "custom",
    "cut", "cute", "cycle", "cygnus", "cypher", "czech",
)


def pick_names(count: int, exclude: set[str]) -> list[str]:
    """Pick `count` random unique names from the pool, excluding any in `exclude`.

    Args:
        count: Number of names to pick
        exclude: Set of names to exclude from selection

    Returns:
        List of randomly selected unique names

    Raises:
        ValueError: If not enough names available after exclusions
    """
    available = [name for name in AGENT_NAMES if name not in exclude]

    if len(available) < count:
        raise ValueError(
            f"Not enough names available: requested {count}, "
            f"but only {len(available)} available after exclusions"
        )

    return random.sample(available, count)
